//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fiscal
    {
        public int FiscalID { get; set; }
        public string FiscalName { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public System.DateTimeOffset ExpectedClosingDate { get; set; }
        public Nullable<System.DateTimeOffset> RefreshDate { get; set; }
        public Nullable<int> RefreshBy { get; set; }
        public Nullable<System.DateTime> ClosePriceDate { get; set; }
        public Nullable<int> ClosePriceBy { get; set; }
        public Nullable<System.DateTimeOffset> ClosingDate { get; set; }
        public Nullable<int> ClosingBy { get; set; }
        public Nullable<System.DateTimeOffset> CancelDate { get; set; }
        public Nullable<int> CancelBy { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public string Notes { get; set; }
        public int Status { get; set; }
        public bool IsClosePrice { get; set; }
        public bool IsCurrent { get; set; }
    }
}
