//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionSystem
    {
        public int OptionID { get; set; }
        public string OptionName { get; set; }
        public string OptionType { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string Value { get; set; }
        public string DataType { get; set; }
        public string Notes { get; set; }
    }
}
