//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefNo
    {
        public int RowID { get; set; }
        public int StoreID { get; set; }
        public string RefType { get; set; }
        public string FormateString { get; set; }
        public int Length { get; set; }
        public Nullable<int> rRefType { get; set; }
        public string SqlQueryRefNo { get; set; }
        public string SqlQueryRefNoSQL { get; set; }
        public string SequenceName { get; set; }
        public bool IsProfixDate { get; set; }
        public bool IsProfixMontYear { get; set; }
        public string Notes { get; set; }
    }
}
