//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public int UnitID { get; set; }
        public string UnitCode { get; set; }
        public string UnitName { get; set; }
        public string Notes { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTimeOffset CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTimeOffset> ModifyDate { get; set; }
        public string SearchString { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public bool IsActive { get; set; }
    }
}
