//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimERP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTimeOffset> ModifyDate { get; set; }
        public int UserTypeID { get; set; }
        public Nullable<System.DateTimeOffset> LastestLogin { get; set; }
        public Nullable<System.DateTimeOffset> LastestLogout { get; set; }
        public Nullable<System.DateTime> PasswordExpire { get; set; }
        public string SystemLanguage { get; set; }
        public string PageDefault { get; set; }
        public string SignatureImage { get; set; }
        public string Avatar { get; set; }
        public bool IsAdminCode { get; set; }
        public string AdminCode { get; set; }
        public bool IsSecondPassword { get; set; }
        public string SecondPassword { get; set; }
        public bool IsSeeAuthorizations { get; set; }
        public bool IsFirstChangePassword { get; set; }
        public Nullable<bool> IsSystem { get; set; }
        public bool IsActive { get; set; }
    }
}
